name: E2E Checks

on:
  # Manual trigger, PRs to main, or push to main. For PRs, tests run only if secret origin is configured.
  workflow_dispatch:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  prekeys-devkeys:
    name: Prekeys & Devkeys
    runs-on: ubuntu-latest
    env:
      ORIGIN_API: ${{ secrets.E2E_ORIGIN_API }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: npm ci

      - name: Skip if no ORIGIN_API configured
        if: ${{ env.ORIGIN_API == '' }}
        run: |
          echo "E2E_ORIGIN_API is not configured. Skipping E2E tests." && exit 0

      - name: Run prekeys/devkeys E2E
        if: ${{ env.ORIGIN_API != '' }}
        run: node scripts/test-prekeys-devkeys.mjs

  messages-secure:
    name: Messages Secure
    runs-on: ubuntu-latest
    needs: prekeys-devkeys
    env:
      ORIGIN_API: ${{ secrets.E2E_ORIGIN_API }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: npm ci

      - name: Skip if no ORIGIN_API configured
        if: ${{ env.ORIGIN_API == '' }}
        run: |
          echo "E2E_ORIGIN_API is not configured. Skipping E2E tests." && exit 0

      - name: Run messages/secure E2E
        if: ${{ env.ORIGIN_API != '' }}
        run: node scripts/test-messages-secure.mjs
